mod config;
mod doctor;
mod node_manager;
mod project_env;
mod project_exec;
mod python_runtime;
mod runtime;
mod runtime_cmd;
mod update;
use anyhow::Result;
use clap::{Parser, Subcommand};
use std::path::PathBuf;
use uuid::Uuid;
use x11_agent::{AgentConfig, AgentRuntime};
use x11_core::mode::AgentMode;
use x11_model::{MockProvider, OpenAiCompatible};
use x11_session::{store::SessionStore, Session};
use x11_tui::stream::run_stream;
#[derive(Debug, Parser)] #[command(name="x11", version, about="X11 Code autonomous coding agent")] struct Cli { #[command(subcommand)] command: Option<Command> }
#[derive(Debug, Subcommand)] enum Command { Run { goal:String, #[arg(short,long)] workspace:Option<PathBuf>, #[arg(long)] model:Option<String>, #[arg(long)] yes:bool, #[arg(long)] max_iterations:Option<u32>, #[arg(long)] session:Option<PathBuf>, #[arg(long="verify",value_name="COMMAND",action=clap::ArgAction::Append)] verify_commands:Vec<String>, #[arg(long)] hooks:bool, #[arg(long)] verification_timeout_ms:Option<u64>, #[arg(long,default_value="normal")] mode:String, #[arg(long)] tui:bool }, Doctor { #[arg(long)] quiet: bool, #[arg(long)] json: bool }, Config { #[command(subcommand)] command: ConfigCommand }, Update { #[arg(long)] check: bool }, Runtime { #[command(subcommand)] command: RuntimeCommand }, Project { #[command(subcommand)] command: ProjectCommand }, Sessions { #[command(subcommand)] command:SessionCommand } }
#[derive(Debug, Subcommand)] enum ConfigCommand { Path, Show }
#[derive(Debug, Subcommand)] enum RuntimeCommand { Status { #[arg(long)] json: bool }, Install { runtime:String, version:String } }
#[derive(Debug, Subcommand)] enum ProjectCommand { Detect { #[arg(short,long)] workspace:Option<PathBuf> }, Env { #[command(subcommand)] command: ProjectEnvCommand }, Run { action:String, #[arg(short,long)] workspace:Option<PathBuf>, #[arg(long)] timeout_ms:Option<u64>, #[arg(long)] execute:bool, #[arg(long,default_value="auto")] sandbox:String } }
#[derive(Debug, Subcommand)] enum ProjectEnvCommand { Status { #[arg(short,long)] workspace:Option<PathBuf>, #[arg(long)] json:bool }, Python { #[arg(short,long)] workspace:Option<PathBuf> } }
#[derive(Debug, Subcommand)] enum SessionCommand { List{#[arg(short,long)]workspace:Option<PathBuf>}, Show{id:Uuid,#[arg(short,long)]workspace:Option<PathBuf>}, Fork{id:Uuid,goal:String,#[arg(short,long)]workspace:Option<PathBuf>} }
fn parse_mode(mode:&str)->Result<AgentMode>{Ok(match mode.to_ascii_lowercase().as_str(){"normal"=>AgentMode::Normal,"plan"=>AgentMode::Plan,"auto"=>AgentMode::Auto,"review"=>AgentMode::Review,other=>anyhow::bail!("unknown mode: {other}; use normal, plan, auto, or review")})}
fn store_for(workspace:PathBuf)->SessionStore{SessionStore::new(workspace.join(".x11/sessions"))}
async fn run_with_provider<P:x11_model::ModelProvider+'static>(goal:String,cfg:AgentConfig,provider:P,tui:bool)->Result<()>{ let mut agent=AgentRuntime::new(goal,cfg,provider); agent.policy=config::policy(&agent.config.workspace)?; let plugin_dir=agent.config.workspace.join(".x11/plugins");if plugin_dir.is_dir(){let count=agent.load_plugins_from(&plugin_dir)?;if count>0{println!("loaded {count} plugin skill(s) from {}",plugin_dir.display());}} let count=agent.load_mcp_configs(&agent.config.workspace).await?;if count>0{println!("loaded {count} MCP tool(s)");} if tui{let approval_requests=agent.enable_interactive_approvals();let broker=agent.approvals.clone();let events=agent.subscribe();let cancel=agent.cancel.clone();let mut handle=tokio::spawn(async move{let mut agent=agent;agent.run().await});let mut stdout=std::io::stdout();let user_command=run_stream(&mut stdout,events,broker,approval_requests).await?;if matches!(user_command,x11_tui::stream::UserCommand::Quit)&&!handle.is_finished(){let _=cancel.send(true);let _=tokio::time::timeout(std::time::Duration::from_secs(2),&mut handle).await;if !handle.is_finished(){handle.abort();}} match handle.await{Ok(Ok(_))=>Ok(()),Ok(Err(err))if matches!(user_command,x11_tui::stream::UserCommand::Quit)=>{if err.to_string().contains("cancel"){Ok(())}else{Err(err)}},Ok(Err(err))=>Err(err),Err(err)if err.is_cancelled()=>Ok(()),Err(err)=>Err(err.into())}}else{let result=agent.run().await;for e in &agent.session.events{println!("{:?}",e);}result.map(|text|{if !text.is_empty(){println!("\n{text}");}})?;Ok(())}}
#[tokio::main] async fn main()->Result<()>{ tracing_subscriber::fmt().with_env_filter("x11=info").init(); match Cli::parse().command{
 Some(Command::Doctor{quiet,json})=>{let checks=doctor::collect();if json{let rows=checks.iter().map(|c|{let status=match c.status{doctor::Status::Ok=>"ok",doctor::Status::Warn=>"warn",doctor::Status::Fail=>"fail"};serde_json::json!({"name":c.name,"status":status,"detail":c.detail})}).collect::<Vec<_>>();println!("{}",serde_json::to_string_pretty(&rows)?);if checks.iter().any(|c|c.status==doctor::Status::Fail){std::process::exit(1);}}else if !quiet{if !doctor::print(false){std::process::exit(1);}}else if !doctor::print(true){std::process::exit(1);}},
 Some(Command::Config{command})=>{match command{ConfigCommand::Path=>{if let Some(path)=config::user_config_path(){println!("{}",path.display());}else{println!("user config path unavailable");}},ConfigCommand::Show=>{let workspace=std::env::current_dir()?;for(key,value)in config::describe(&workspace)?{println!("{key:<18}{value}");}}}},
 Some(Command::Update{check})=>{update::run(check).await?;},
 Some(Command::Runtime{command})=>{match command{RuntimeCommand::Status{json}=>runtime_cmd::print_status(json)?,RuntimeCommand::Install{runtime,version}=>runtime_cmd::install(&runtime,&version).await?;}},
 Some(Command::Project{command})=>{let workspace=match &command{ProjectCommand::Detect{workspace}|ProjectCommand::Run{workspace,..}=>workspace.clone().unwrap_or(std::env::current_dir()?),ProjectCommand::Env{command:ProjectEnvCommand::Status{workspace,..}}|ProjectCommand::Env{command:ProjectEnvCommand::Python{workspace}}=>workspace.clone().unwrap_or(std::env::current_dir()?)};match command{ProjectCommand::Detect{..}=>println!("{:?}",project_exec::detect(&workspace)),ProjectCommand::Env{command:ProjectEnvCommand::Status{json,..}}=>project_env::print_status(&workspace,json)?,ProjectCommand::Env{command:ProjectEnvCommand::Python{..}}=>project_env::create_python(&workspace).await?,ProjectCommand::Run{action,timeout_ms,execute,sandbox,..}=>{let kind=project_exec::detect(&workspace);let plan=project_exec::plan(&workspace,kind,&action)?;let sandbox_mode=x11_agent::tool_executor::sandbox::Mode::parse(&sandbox)?;let code=project_exec::execute(&plan,timeout_ms.unwrap_or(300_000),!execute,sandbox_mode).await?;if code!=0{std::process::exit(code);}}}},
 Some(Command::Run{goal,workspace,model,yes,max_iterations,session,verify_commands,hooks,verification_timeout_ms,mode,tui})=>{let mut cfg=AgentConfig::default();cfg.workspace=workspace.unwrap_or(std::env::current_dir()?);cfg.mode=parse_mode(&mode)?;if let Some(m)=model{cfg.model=m;}cfg.auto_approve=yes||matches!(cfg.mode,AgentMode::Auto);cfg.hooks_enabled=hooks;if let Some(n)=max_iterations{cfg.max_iterations=n.max(1);}if let Some(ms)=verification_timeout_ms{cfg.verification_timeout_ms=ms.clamp(100,600_000);}if !verify_commands.is_empty(){cfg.verification_commands=verify_commands;}cfg.session_path=session.or_else(||Some(Session::default_path(&cfg.workspace)));if let(Ok(key),Ok(base))=(std::env::var("X11_API_KEY"),std::env::var("X11_BASE_URL")){run_with_provider(goal,cfg,OpenAiCompatible::new(base,key),tui).await?;}else{run_with_provider(goal,cfg,MockProvider,tui).await?;}},
 Some(Command::Sessions{command})=>{let workspace=match &command{SessionCommand::List{workspace}|SessionCommand::Show{workspace,..}|SessionCommand::Fork{workspace,..}=>workspace.clone().unwrap_or(std::env::current_dir()?)};let store=store_for(workspace);match command{SessionCommand::List{..}=>{for(id,updated,goal)in store.list().await?{println!("{id}  {updated}  {goal}");}},SessionCommand::Show{id,..}=>{let s=store.load(id).await?;println!("{}\n{}\n{} events",s.id,s.goal,s.events.len());},SessionCommand::Fork{id,goal,..}=>{let s=store.load(id).await?;let fork=s.fork(goal);let path=store.save(&fork).await?;println!("forked {} -> {}\n{}",s.id,fork.id,path.display());}}}
 None=>println!("X11 Code. Use `x11 doctor`, `x11 config path|show`, `x11 update`, `x11 runtime status`, `x11 runtime install <node|python> <version>`, `x11 project detect`, `x11 project env status`, `x11 project env python`, `x11 project run <install|test|build> --sandbox auto|strict|off`, `x11 run <goal> [--tui]`, or `x11 sessions list`.)}
 Ok(()) }