pub mod commands;
pub mod cosmic;
pub mod stream;
pub mod swarm;
pub mod live_swarm;
pub mod cosmic_state;

use crossterm::{cursor::MoveTo,event::{self, Event, KeyCode, KeyEvent, KeyModifiers},execute,style::{Attribute, Print, SetAttribute},terminal::{self, Clear, ClearType, EnterAlternateScreen, LeaveAlternateScreen}};
use std::{collections::VecDeque, io::{self, Write}, time::Duration};
use x11_agent::swarm_events::{SwarmEvent, SwarmEventKind};
use x11_protocol::AgentEvent;
use crate::commands::{help_lines, parse, Command};
use crate::cosmic::CosmicField;
use crate::cosmic_state::CosmicPhase;

const MAX_LOG_LINES: usize = 500;

#[derive(Debug, Clone)] pub struct ApprovalRequest { pub call_id: uuid::Uuid, pub tool: String, pub reason: String }
#[derive(Debug)] pub struct TuiState { pub state:String,pub logs:VecDeque<String>,pub agents:Vec<(String,String,String)>,pub approval:Option<ApprovalRequest>,pub todo:Vec<(String,String)>,pub cosmic:CosmicField,pub command_mode:bool,pub input:String,pub notice:Option<String> }
impl Default for TuiState { fn default()->Self{Self{state:"idle".into(),logs:VecDeque::new(),agents:Vec::new(),approval:None,todo:Vec::new(),cosmic:CosmicField::new(120,36),command_mode:false,input:String::new(),notice:None}} }
impl TuiState {
 pub fn apply(&mut self,event:&AgentEvent){match event{
  AgentEvent::SessionStarted{..}=>self.state="starting".into(),AgentEvent::StateChanged{state}=>self.state=state.clone(),AgentEvent::AssistantDelta{text}=>self.push_log(format!("assistant: {text}")),AgentEvent::ToolRequested{tool,..}=>self.push_log(format!("tool → {tool}")),AgentEvent::ToolCompleted{tool,success,output,..}=>self.push_log(format!("{tool} {}: {output}",if *success{"✓"}else{"✗"})),
  AgentEvent::ApprovalRequested{call_id,tool,reason,..}=>{self.approval=Some(ApprovalRequest{call_id:*call_id,tool:tool.clone(),reason:reason.clone()});self.push_log(format!("approval required: {tool}"));},
  AgentEvent::ApprovalResolved{tool,approved,..}=>{self.push_log(format!("approval {}: {tool}",if *approved{"granted"}else{"denied"}));if self.approval.as_ref().is_some_and(|a|a.tool==*tool){self.approval=None;}},
  AgentEvent::SubagentStarted{agent_id,role,..}=>self.agents.push((agent_id.clone(),role.clone(),"running".into())),AgentEvent::SubagentFinished{agent_id,success,summary}=>{if let Some(a)=self.agents.iter_mut().find(|a|a.0==*agent_id){a.2=if *success{"done"}else{"failed"}.into();}self.push_log(format!("subagent {agent_id}: {summary}"));},
  AgentEvent::TodoChanged{task_id,title,status}=>{let key=task_id.to_string();if let Some(i)=self.todo.iter_mut().find(|(id,_)|*id==key){i.1=format!("{title} [{status}]")}else{self.todo.push((key,format!("{title} [{status}]")));}},
  AgentEvent::CheckpointCreated{id,note}=>self.push_log(format!("checkpoint {id}: {note}")),AgentEvent::Verification{passed,summary}=>{self.push_log(format!("verify {}: {summary}",if *passed{"✓"}else{"✗"}));self.cosmic.set_phase(if *passed { CosmicPhase::Verifying } else { CosmicPhase::Failed });},AgentEvent::Error{message}=>{self.push_log(format!("error: {message}"));self.cosmic.set_phase(CosmicPhase::Failed)},AgentEvent::SessionFinished{success}=>{self.state=if *success{"completed"}else{"failed"}.into();self.cosmic.set_phase(if *success { CosmicPhase::Completed } else { CosmicPhase::Failed });},AgentEvent::PlanCreated{steps}=>self.push_log(format!("plan: {} steps",steps.len()))};self.cosmic.tick();}
 pub fn apply_swarm_event(&mut self,event:&SwarmEvent){let phase=CosmicPhase::from_event(&event.kind);self.cosmic.set_phase(phase);match event.kind{SwarmEventKind::ConflictDetected=>self.push_log("swarm conflict detected".into()),SwarmEventKind::ResolverStarted=>self.push_log("resolver started".into()),SwarmEventKind::ResolverProposed=>self.push_log("resolver proposal ready".into()),SwarmEventKind::ResolverApplied=>self.push_log("resolver applied".into()),SwarmEventKind::ResolverRolledBack=>self.push_log("resolver rolled back".into()),SwarmEventKind::VerificationStarted=>self.push_log("verification started".into()),SwarmEventKind::VerificationPassed=>self.push_log("verification passed".into()),SwarmEventKind::VerificationFailed=>self.push_log("verification failed".into()),SwarmEventKind::SwarmCompleted=>self.state="completed".into(),SwarmEventKind::TaskFailed|SwarmEventKind::TaskCancelled=>self.state="failed".into(),_=>{}};self.cosmic.tick();}
 pub fn push_log(&mut self,line:String){for part in line.lines(){self.logs.push_back(part.to_owned());}while self.logs.len()>MAX_LOG_LINES{self.logs.pop_front();}}
 pub fn command_submit(&mut self)->Option<Command>{let value=self.input.trim().to_owned();self.input.clear();self.command_mode=false;parse(&value)}
}
pub fn draw_snapshot<W:Write>(out:&mut W,state:&TuiState,width:u16,height:u16)->anyhow::Result<()>{execute!(out,MoveTo(0,0),Clear(ClearType::All))?;let stars=state.cosmic.overlay(width.min(120),height.min(36));for(y,row)in stars.lines().enumerate(){if y as u16>=height{break}execute!(out,MoveTo(0,y as u16),Print(row))?;}execute!(out,MoveTo(0,0),SetAttribute(Attribute::Bold),Print(" ✦ X11 CODE"),SetAttribute(Attribute::Reset))?;let status=format!("state: {}",state.state);execute!(out,MoveTo(width.saturating_sub(status.len() as u16+1),0),Print(status))?;let sidebar=width.min(30);execute!(out,MoveTo(0,2),Print(" AGENTS"))?;for(i,(id,role,status))in state.agents.iter().enumerate().take(height.saturating_sub(8)as usize){execute!(out,MoveTo(0,3+i as u16),Print(format!(" {:<11} {:<10} {}",id,role,status)))?;}execute!(out,MoveTo(sidebar,2),Print(" ACTIVITY"))?;let available=height.saturating_sub(8)as usize;for(i,line)in state.logs.iter().rev().take(available).rev().enumerate(){let max=width.saturating_sub(sidebar+1)as usize;let text=if line.len()>max{format!("{}…",&line[..max.saturating_sub(1)])}else{line.clone()};execute!(out,MoveTo(sidebar,3+i as u16),Print(text))?;}if let Some(a)=&state.approval{execute!(out,MoveTo(1,height.saturating_sub(4)),SetAttribute(Attribute::Bold),Print(format!(" APPROVAL: {} | {} | [y]es [n]o",a.tool,a.reason)),SetAttribute(Attribute::Reset))?;}else if state.command_mode{execute!(out,MoveTo(1,height.saturating_sub(3)),Print(format!(" :{}",state.input)))}else{execute!(out,MoveTo(1,height.saturating_sub(3)),Print(" : command  |  q quit  |  y/n approval"))?;}if let Some(n)=&state.notice{execute!(out,MoveTo(1,height.saturating_sub(2)),Print(n))?;}out.flush()?;Ok(())}
pub fn run<I>(mut events:I)->anyhow::Result<()> where I:Iterator<Item=AgentEvent>{let mut stdout=io::stdout();terminal::enable_raw_mode()?;execute!(stdout,EnterAlternateScreen,Clear(ClearType::All))?;let result=(||->anyhow::Result<()>{let mut state=TuiState::default();loop{if let Some(e)=events.next(){state.apply(&e);}let(width,height)=terminal::size()?;draw_snapshot(&mut stdout,&state,width,height)?;if event::poll(Duration::from_millis(80))?{match event::read()?{Event::Key(KeyEvent{code:KeyCode::Char('q'),modifiers,..})if modifiers.is_empty()=>break,Event::Key(KeyEvent{code:KeyCode::Char('c'),modifiers,..})if modifiers.contains(KeyModifiers::CONTROL)=>break,Event::Key(KeyEvent{code:KeyCode::Enter,..})if state.command_mode=>{if let Some(c)=state.command_submit(){match c{Command::Quit=>break,Command::Help=>for line in help_lines(){state.push_log((*line).into())},other=>state.notice=Some(format!("command: {other:?}"))}}},Event::Key(KeyEvent{code:KeyCode::Char(':'),..})if !state.command_mode=>state.command_mode=true,Event::Key(KeyEvent{code:KeyCode::Backspace,..})if state.command_mode=>{state.input.pop();},Event::Key(KeyEvent{code:KeyCode::Char(c),..})if state.command_mode=>state.input.push(c),_=>{}}}if matches!(state.state.as_str(),"completed"|"failed"){break;}}Ok(())})();execute!(stdout,LeaveAlternateScreen)?;terminal::disable_raw_mode()?;result}
#[cfg(test)]mod tests{use super::*;use uuid::Uuid;#[test]fn state_tracks_subagents_and_commands(){let id=Uuid::new_v4();let mut s=TuiState::default();s.apply(&AgentEvent::SubagentStarted{agent_id:"coder".into(),role:"Implementer".into(),session_id:x11_protocol::SessionId(id)});assert_eq!(s.agents[0].2,"running");s.input="/plan".into();assert_eq!(s.command_submit(),Some(Command::Plan));let event=SwarmEvent::new(id,SwarmEventKind::ConflictDetected);s.apply_swarm_event(&event);assert_eq!(s.cosmic.phase(),CosmicPhase::Conflict);}}
